import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { DatasetProvider } from "./context/DatasetContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <header className="w-full bg-white px-6 py-4 border-b">
          <h1 className="text-xl font-semibold text-gray-900">
            Metrics Dashboard
          </h1>
        </header>

        <DatasetProvider>{children}</DatasetProvider>
        <footer className="w-full border-t bg-white px-6 py-4">
          <div className="text-right text-sm text-gray-600">
            © {new Date().getFullYear()} Noureddin Khalaf · Contact: 0782622515
          </div>
        </footer>
      </body>
    </html>
  );
}
